# Copyright (C) 2019 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

version: "2"
services:
  cleandev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ".:/vagrant"
    environment:
     - PYTHONDONTWRITEBYTECODE=true
     - NODE_PATH=/vagrant-dev/node_modules/
     - GGRC_DATABASE_HOST=db
  db:
    image: mysql:5.6
    volumes:
     - "./provision/docker/mysql:/etc/mysql/conf.d"
    environment:
     - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql/:rw,noexec,nosuid,size=1G
