# Copyright (C) 2017 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>  


FROM selenium/standalone-chrome

USER root
COPY ./provision/docker/selenium.bashrc.j2 /root/.bashrc
RUN apt-get update && apt-get install -y python python-pip python-setuptools

COPY ./src/requirements-selenium.txt /tmp/requirements.txt
RUN pip install pip \
  && pip install -r /tmp/requirements.txt

RUN usermod -u 1000 seluser

WORKDIR /selenium
USER seluser
