"""Adding company control

Revision ID: 2793676d8016
Revises: 14a59edf62de
Create Date: 2013-06-18 22:37:37.714176

"""

# revision identifiers, used by Alembic.
revision = '2793676d8016'
down_revision = '14a59edf62de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('company_control', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controls', 'company_control')
    ### end Alembic commands ###
