## Copyright (C) 2017 Google Inc.
## Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

.. WARNING! This file is autogenerated and should not be edited manually.

${h.title(title)}

..  toctree::
    :maxdepth: 3

    % for package in packages:
    ${package.name}/index
    % endfor
