"""Person.email must be unique

Revision ID: 2bf7c04016c9
Revises: 2b709b655bf
Create Date: 2013-07-24 02:16:06.282258

"""

# revision identifiers, used by Alembic.
revision = '2bf7c04016c9'
down_revision = '2b709b655bf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_people_email', 'people', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_people_email', 'people', type_='unique')
    ### end Alembic commands ###
