# Copyright (C) 2013 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: dan@reciprocitylabs.com
# Maintained By: dan@reciprocitylabs.com

"""Add controls.company_control, drop directives.company

Revision ID: 52a791eb9a71
Revises: 2793676d8016
Create Date: 2013-06-20 00:15:37.666184

"""

# revision identifiers, used by Alembic.
revision = '52a791eb9a71'
down_revision = '2793676d8016'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('company_control', sa.Boolean(), nullable=True))
    op.drop_column(u'directives', u'company')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'directives', sa.Column(u'company', mysql.TINYINT(display_width=1), nullable=False))
    op.drop_column('controls', 'company_control')
    ### end Alembic commands ###
