# Copyright (C) 2015 Google Inc., authors, and contributors <see AUTHORS file>
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
# Created By: anze@reciprocitylabs.com
# Maintained By: anze@reciprocitylabs.com


"""Indexes on updated_at for all base objects

Revision ID: 63fc392c91a
Revises: 15d26db08b54
Create Date: 2014-09-12 22:59:56.977642

"""

# revision identifiers, used by Alembic.
revision = '63fc392c91a'
down_revision = '15d26db08b54'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audits_updated_at', 'audits', ['updated_at'], unique=False)
    op.create_index('ix_background_tasks_updated_at', 'background_tasks', ['updated_at'], unique=False)
    op.create_index('ix_calendar_entries_updated_at', 'calendar_entries', ['updated_at'], unique=False)
    op.create_index('ix_categories_updated_at', 'categories', ['updated_at'], unique=False)
    op.create_index('ix_categorizations_updated_at', 'categorizations', ['updated_at'], unique=False)
    op.create_index('ix_control_controls_updated_at', 'control_controls', ['updated_at'], unique=False)
    op.create_index('ix_control_sections_updated_at', 'control_sections', ['updated_at'], unique=False)
    op.create_index('ix_controls_updated_at', 'controls', ['updated_at'], unique=False)
    op.create_index('ix_data_assets_updated_at', 'data_assets', ['updated_at'], unique=False)
    op.create_index('ix_directive_controls_updated_at', 'directive_controls', ['updated_at'], unique=False)
    op.create_index('ix_directive_sections_updated_at', 'directive_sections', ['updated_at'], unique=False)
    op.create_index('ix_directives_updated_at', 'directives', ['updated_at'], unique=False)
    op.create_index('ix_documents_updated_at', 'documents', ['updated_at'], unique=False)
    op.create_index('ix_facilities_updated_at', 'facilities', ['updated_at'], unique=False)
    op.create_index('ix_helps_updated_at', 'helps', ['updated_at'], unique=False)
    op.create_index('ix_markets_updated_at', 'markets', ['updated_at'], unique=False)
    op.create_index('ix_meetings_updated_at', 'meetings', ['updated_at'], unique=False)
    op.create_index('ix_notification_configs_updated_at', 'notification_configs', ['updated_at'], unique=False)
    op.create_index('ix_notification_objects_updated_at', 'notification_objects', ['updated_at'], unique=False)
    op.create_index('ix_notification_recipients_updated_at', 'notification_recipients', ['updated_at'], unique=False)
    op.create_index('ix_notifications_updated_at', 'notifications', ['updated_at'], unique=False)
    op.create_index('ix_object_controls_updated_at', 'object_controls', ['updated_at'], unique=False)
    op.create_index('ix_object_documents_updated_at', 'object_documents', ['updated_at'], unique=False)
    op.create_index('ix_object_objectives_updated_at', 'object_objectives', ['updated_at'], unique=False)
    op.create_index('ix_object_owners_updated_at', 'object_owners', ['updated_at'], unique=False)
    op.create_index('ix_object_people_updated_at', 'object_people', ['updated_at'], unique=False)
    op.create_index('ix_object_sections_updated_at', 'object_sections', ['updated_at'], unique=False)
    op.create_index('ix_objective_controls_updated_at', 'objective_controls', ['updated_at'], unique=False)
    op.create_index('ix_objectives_updated_at', 'objectives', ['updated_at'], unique=False)
    op.create_index('ix_options_updated_at', 'options', ['updated_at'], unique=False)
    op.create_index('ix_org_groups_updated_at', 'org_groups', ['updated_at'], unique=False)
    op.create_index('ix_people_updated_at', 'people', ['updated_at'], unique=False)
    op.create_index('ix_products_updated_at', 'products', ['updated_at'], unique=False)
    op.create_index('ix_program_controls_updated_at', 'program_controls', ['updated_at'], unique=False)
    op.create_index('ix_program_directives_updated_at', 'program_directives', ['updated_at'], unique=False)
    op.create_index('ix_programs_updated_at', 'programs', ['updated_at'], unique=False)
    op.create_index('ix_projects_updated_at', 'projects', ['updated_at'], unique=False)
    op.create_index('ix_relationship_types_updated_at', 'relationship_types', ['updated_at'], unique=False)
    op.create_index('ix_relationships_updated_at', 'relationships', ['updated_at'], unique=False)
    op.create_index('ix_requests_updated_at', 'requests', ['updated_at'], unique=False)
    op.create_index('ix_responses_updated_at', 'responses', ['updated_at'], unique=False)
    op.create_index('ix_revisions_updated_at', 'revisions', ['updated_at'], unique=False)
    op.create_index('ix_section_objectives_updated_at', 'section_objectives', ['updated_at'], unique=False)
    op.create_index('ix_sections_updated_at', 'sections', ['updated_at'], unique=False)
    op.create_index('ix_systems_updated_at', 'systems', ['updated_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_systems_updated_at', table_name='systems')
    op.drop_index('ix_sections_updated_at', table_name='sections')
    op.drop_index('ix_section_objectives_updated_at', table_name='section_objectives')
    op.drop_index('ix_revisions_updated_at', table_name='revisions')
    op.drop_index('ix_responses_updated_at', table_name='responses')
    op.drop_index('ix_requests_updated_at', table_name='requests')
    op.drop_index('ix_relationships_updated_at', table_name='relationships')
    op.drop_index('ix_relationship_types_updated_at', table_name='relationship_types')
    op.drop_index('ix_projects_updated_at', table_name='projects')
    op.drop_index('ix_programs_updated_at', table_name='programs')
    op.drop_index('ix_program_directives_updated_at', table_name='program_directives')
    op.drop_index('ix_program_controls_updated_at', table_name='program_controls')
    op.drop_index('ix_products_updated_at', table_name='products')
    op.drop_index('ix_people_updated_at', table_name='people')
    op.drop_index('ix_org_groups_updated_at', table_name='org_groups')
    op.drop_index('ix_options_updated_at', table_name='options')
    op.drop_index('ix_objectives_updated_at', table_name='objectives')
    op.drop_index('ix_objective_controls_updated_at', table_name='objective_controls')
    op.drop_index('ix_object_sections_updated_at', table_name='object_sections')
    op.drop_index('ix_object_people_updated_at', table_name='object_people')
    op.drop_index('ix_object_owners_updated_at', table_name='object_owners')
    op.drop_index('ix_object_objectives_updated_at', table_name='object_objectives')
    op.drop_index('ix_object_documents_updated_at', table_name='object_documents')
    op.drop_index('ix_object_controls_updated_at', table_name='object_controls')
    op.drop_index('ix_notifications_updated_at', table_name='notifications')
    op.drop_index('ix_notification_recipients_updated_at', table_name='notification_recipients')
    op.drop_index('ix_notification_objects_updated_at', table_name='notification_objects')
    op.drop_index('ix_notification_configs_updated_at', table_name='notification_configs')
    op.drop_index('ix_meetings_updated_at', table_name='meetings')
    op.drop_index('ix_markets_updated_at', table_name='markets')
    op.drop_index('ix_helps_updated_at', table_name='helps')
    op.drop_index('ix_facilities_updated_at', table_name='facilities')
    op.drop_index('ix_documents_updated_at', table_name='documents')
    op.drop_index('ix_directives_updated_at', table_name='directives')
    op.drop_index('ix_directive_sections_updated_at', table_name='directive_sections')
    op.drop_index('ix_directive_controls_updated_at', table_name='directive_controls')
    op.drop_index('ix_data_assets_updated_at', table_name='data_assets')
    op.drop_index('ix_controls_updated_at', table_name='controls')
    op.drop_index('ix_control_sections_updated_at', table_name='control_sections')
    op.drop_index('ix_control_controls_updated_at', table_name='control_controls')
    op.drop_index('ix_categorizations_updated_at', table_name='categorizations')
    op.drop_index('ix_categories_updated_at', table_name='categories')
    op.drop_index('ix_calendar_entries_updated_at', table_name='calendar_entries')
    op.drop_index('ix_background_tasks_updated_at', table_name='background_tasks')
    op.drop_index('ix_audits_updated_at', table_name='audits')
    ### end Alembic commands ###
