# Copyright (C) 2018 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
"""
add folder column

Create Date: 2018-07-25 17:29:07.099021
"""
# disable Invalid constant name pylint warning for mandatory Alembic variables.
# pylint: disable=invalid-name

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2566da5aeca8'
down_revision = '20ca15a10d12'


def upgrade():
  """Upgrade database schema and/or data, creating a new revision."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('access_groups',
                sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('clauses', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('data_assets', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('directives', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('facilities', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('issues', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('markets', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('metrics', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('objectives', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('org_groups', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('products', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('projects', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('requirements', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('systems', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('vendors', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('product_groups',
                sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('technology_environments',
                sa.Column('folder', sa.Text(), nullable=False))
  # ### end Alembic commands ###


def downgrade():
  """Downgrade database schema and/or data back to the previous revision."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('vendors', 'folder')
  op.drop_column('systems', 'folder')
  op.drop_column('requirements', 'folder')
  op.drop_column('projects', 'folder')
  op.drop_column('products', 'folder')
  op.drop_column('org_groups', 'folder')
  op.drop_column('objectives', 'folder')
  op.drop_column('metrics', 'folder')
  op.drop_column('markets', 'folder')
  op.drop_column('issues', 'folder')
  op.drop_column('facilities', 'folder')
  op.drop_column('directives', 'folder')
  op.drop_column('data_assets', 'folder')
  op.drop_column('clauses', 'folder')
  op.drop_column('access_groups', 'folder')
  op.drop_column('product_groups', 'folder')
  op.drop_column('technology_environments', 'folder')
  # ### end Alembic commands ###
