# Copyright (C) 2018 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
"""
add folde field

Create Date: 2018-07-25 18:23:56.809670
"""
# disable Invalid constant name pylint warning for mandatory Alembic variables.
# pylint: disable=invalid-name

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '1d5aadd8ef75'
down_revision = '3a7d002f930e'


def upgrade():
  """Upgrade database schema and/or data, creating a new revision."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('risks', sa.Column('folder', sa.Text(), nullable=False))
  op.add_column('threats', sa.Column('folder', sa.Text(), nullable=False))
  # ### end Alembic commands ###


def downgrade():
  """Downgrade database schema and/or data back to the previous revision."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('risks', 'folder')
  op.drop_column('threats', 'folder')
  # ### end Alembic commands ###
